keypair: init_key_pair
django_project_name: django-imager
security_group: ssh-access
instance_type: t2.micro
ami: ami-d732f0b7
vpc_subnet_id: subnet-24c18852
region: us-west-2
instance_tags: {"Name": "{{ django_project_name }}"}
root_ebs_size: 8
zone: us-west-2a
instance_profile_name: "{{ django_project_name }}"
num_instances: 1
