user_home: /home/ubuntu
django_home: "{{ user_home }}/{{ django_project_name }}"
django_project_name: django_imager
venv_home: "{{ user_home }}/venv"
media_path: "{{ django_home }}/media"
static_path: "{{ django_home }}/static"
rds_db_instance: django-imager-db
system_packages:
  - build-essential
  - python-dev
  - python-pip
  - postgresql-client
  - libpq-dev
  - python-psycopg2
  - git
  - python-virtualenv
  - libjpeg-dev
  - libtiff-dev
  - libjpeg8-dev
  - zlib1g-dev
  - libfreetype6-dev
  - liblcms2-dev
  - libwebp-dev
  - tcl8.6-dev
  - tk8.6-dev

repo: https://github.com/ilikesounds/django-imager.git
repo_version: master
django_settings: imagersite.settings
DBUSER: imageruser
DBPORT: 5432
DBNAME: imager_db
DBPASS: "{{ DBPASS_VAULT }}"
DEBUG: False
EMAIL_USER: picturecrap
EMAIL_DEFAULT: "picturecrap@gmail.com"
app_user: 'www-data'
