---

- name: Install System Packages
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  sudo: yes
  with_items: "{{ system_packages }}"

- name: Clone Django Repository
  git: repo={{ repo }}
    dest={{ django_home }}
    force=yes depth=1
    verision={{ repo_version }}

- name: Install Python Dependencies
  pip:
    virtualenv: "{{ venv_home }}"
    state: present
    requirements: "{{ django_home }}/requirements.pip"

- name: Get DB Hostvars
  set_fact:
    db_host: "{{ hostvars[groups[rds_db_instance][0]] }}"
    debug: db_host

- name: Set DB URL
  set_fact:
    db_url: "{{ db_host.ec2_engine }}://{{ db_host.ec2_master_username }}:{{ DBPASS }}@{{ db_host.ec2__address }}:{{ db_host.ec2__port }}/{{ db_host.ec2_DBName }}"

- name: Run Migrations
  environment:
    DJANGO_SECURITY_KEY: "{{ DJANGO_SECURITY_KEY }}"
    DBURL: "{{ db_host.ec2__address }}"
    DBUSER: "{{ DBUSER }}"
    DBPORT: "{{ DBPORT }}"
    DBPASS: "{{ DBPASS }}"
    DBNAME: "{{ DBNAME }}"
    EMAIL_USER: "{{ EMAIL_USER }}"
    EMAIL_DEFAULT: "{{ EMAIL_DEFAULT }}"
    EMAIL_PW: "{{ EMAIL_PW }}"
    DEBUG: False
  django_manage:
    virtualenv: "{{ venv_home }}"
    app_path: "{{ django_home }}"
    settings: "{{ django_settings }}"
    command: migrate

- name: Change Media Owner
  sudo: yes
  file: path={{ media_path }} owner={{ app_user }} group={{ app_user }} recurse=yes state=directory mode=775

- name: Change Static Owner
  sudo: yes
  file: path={{ static_path }} owner={{ app_user }} group={{ app_user }} recurse=yes state=directory mode=775


- name: Collect Static Files
  become: true
  environment:
    django_security_key: "{{ DJANGO_SECURITY_KEY }}"
    DBURL: "{{ db_host.ec2__address }}"
    DBUSER: "{{ DBUSER }}"
    DBPORT: "{{ DBPORT }}"
    DBPASS: "{{ DBPASS }}"
    DBNAME: "{{ DBNAME }}"
    EMAIL_USER: "{{ EMAIL_USER }}"
    EMAIL_DEFAULT: "{{ EMAIL_DEFAULT }}"
    EMAIL_PW: "{{ EMAIL_PW }}"
    DEBUG: False
  django_manage:
    virtualenv: "{{ venv_home }}"
    app_path: "{{ django_home }}"
    settings: "{{ django_project_name }}.settings"
    command: collectstatic
